### ISSUE TITLE
Video players stay black

### ISSUE THREAD

**Issue by 2fst4u** [bootsie123/F1-Web-Viewer#33] opened 2021-07-18 03:54 UTC
**Describe the bug**
Streams don't play at all. Video players stay black.

**To Reproduce**
1. open a stream as normal and click the play button
2. Nothing happens

**Expected behavior**
Stream begins to play

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge (chromium) and Firefox 
 - Web version

**F1TV Account (please complete the following information):**
 - Subscription Type: Pro
 - Country: New Zealand

**Additional context**
Browser console shows the following errors:

`Tracking Prevention blocked access to storage for https://www.google-analytics.com/g/collect?v=2&tid=G-QH40ELPHB6&gtm=2oe7e0&_p=1197533762&sr=1200x800&ul=en-nz&cid=710191642.1626579773&_s=2&dl=https%3A%2F%2Ff1webviewer.netlify.app%2F&dt=F1%20Web%20Viewer&sid=1626579772&sct=1&seg=1&en=user_engagement&_et=15778.
f1webviewer.netlify.app/:1 Tracking Prevention blocked a Ping request to https://www.google-analytics.com/g/collect?v=2&tid=G-QH40ELPHB6&gtm=2oe7e0&_p=1169701885&sr=1200x800&ul=en-nz&cid=710191642.1626579773&_s=1&dl=https%3A%2F%2Ff1webviewer.netlify.app%2F&dt=F1%20Web%20Viewer&sid=1626579772&sct=1&seg=1&en=page_view.
www.google-analytics.com/g/collect?v=2&tid=G-QH40ELPHB6&gtm=2oe7e0&_p=1169701885&sr=1200x800&ul=en-nz&cid=710191642.1626579773&_s=1&dl=https%3A%2F%2Ff1webviewer.netlify.app%2F&dt=F1%20Web%20Viewer&sid=1626579772&sct=1&seg=1&en=page_view:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://d33wubrfki0l68.cloudfront.net/bundles/index.2ae109a3.js.map;: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

I turned off the tracker blocking and it gets rid of the errors about that, but doesn't fix the issue. I have also changed network in case the network was blocking something. Browser ad block is disabled also.

I'm not too sure what's going on, th video just stays black as if tthe play button did nothing.

**Comment by bootsie123** [comment] 2021-07-18 11:16
Thanks for the report! I'll try to fix this as soon as possible since it's a major issue. I'm not sure if I'll be able to fix it before the race, but I'll try!

**Comment by bootsie123** [comment] 2021-07-18 12:29
Hmm. I've tried to reproduce this on Chrome and Edge without success. Are you watching while live?

**Comment by 2fst4u** [comment] 2021-07-18 13:29
No sorry this was a replay

**Comment by bootsie123** [comment] 2021-07-18 14:44
Interesting. Have you tried logging out and back in? (You would get an error message in the consolelog though if this was the case). I assume everything works fine if you use the F1TV website?

**Comment by 2fst4u** [comment] 2021-07-19 00:43
Yea regular F1TV works fine. Don't worry it's not high priority if I seem
to be the only person with this issue but I'm curious to know what's
causing it haha.

I've tried a couple of times in different browsers in different locations
so that's required seperate logging in each time yes.

**Comment by bootsie123** [comment] 2021-07-20 16:06
I'm pretty curious about what's causing it too haha. In the developer tools, can you open the network tab and then navigate to the site and try to load a video? It should log the requests. Could you then press the download button and send me the HAR file?

**Comment by bootsie123** [comment] 2021-09-11 23:27
Quick update to keep everyone in the loop. I did end up receiving the HAR file via email and it seems there is an error when a video tries to load causing it to show black instead. The error is as follows:

`F1_FER technical package is available in your region after Current Season ends since 2021-08-01T17:00:00+02:00`

Considering regular F1TV works fine, I'm not entirely sure where the problem lies. For right now I'm going to close this issue and mark it as `wontfix`. However, if there are any leads with this on my side or if anyone else experiences this issue then I'll definitely open it back up

**Closed by bootsie123** 2021-09-11 23:27 UTC
Labels: bug, wontfix

**Comment by bootsie123** [comment] 2021-09-11 23:28
@2fst4u Just curious, what happens if you try to use the self-hosted version of the site? I wondering if something weird is happening with the CORS proxy. Have you also tried a different device?

**Comment by 2fst4u** [comment] 2021-09-12 00:43
Have tried a different device and the same thing happens. I haven't tried self hosting yet as I'm hanging out for that arm docker release. When that gets pushed to dockerhub I can give it a try.

**Comment by bootsie123** [comment] 2021-09-17 12:24
Sounds good! I've been trying to setup an automated release for the multiarch image, although it's been taking a bit of time. Hopefully I'll be able to get it done in the next few days. If not, I'll just manually build and release it for now
