### ISSUE TITLE
EVERY THING got 400 Bad Request

### ISSUE THREAD

**Issue by pjarayuzu** [bootsie123/F1-Web-Viewer#55] opened 2022-02-19 11:51 UTC
**Description**
During to F12, every Request is Status Code: 400 Bad Request. After my research, i think it lose some cookie from the response of MASTER m3u8. 

**Desktop:**
 - OS: Win 10
 - Browser: chrome
 - Version:  97.0

**F1TV Account:**
 - Subscription Type: Access
 - Country: CN

**Comment by bootsie123** [comment] 2022-02-19 19:21
Hi! Thanks for the bug report! I'm currently working on fixing this as we speak. However, since this issue is more or less a duplicate of issue #35, I'm going to close and lock this. Any other discussion should happen over there just so we can keep everything in one place. I'm add an update over there at the end of today on what the current progress is

**Closed by bootsie123** 2022-02-19 19:21 UTC
Labels: bug
